#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "timeout 60s /root/autostart/fm350gl.sh"
    procd_set_param respawn 10 3 0    
    procd_close_instance
}
